name: connectionno_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  equatable: ^2.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.1
  uuid: ^4.5.2
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  youtube_player_flutter: ^9.1.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logoW.png
  # branding: assets/ai_powered_tag.png 
  color_dark: "#000000"
  image_dark: assets/logoD.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoW.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logoW.png"


flutter:

  uses-material-design: true


  assets:
    - assets/logoD.png
    - assets/logoW.png

